# Generated by Django 4.1.10 on 2023-11-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='addressline1',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='addressline2',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
