# Generated by Django 4.1.10 on 2023-11-29 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_remove_userprofile_addressline1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useradd',
            unique_together={('user', 'addressline1', 'addressline2', 'pincode', 'city', 'state')},
        ),
    ]
