# Generated by Django 4.1.10 on 2023-11-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useradd_user_alter_useradd_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradd',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
