# Generated by Django 4.1.10 on 2023-11-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bag_user_wishlistitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/second_background'),
        ),
    ]
