# Generated by Django 4.1.10 on 2023-11-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_second_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
