# Generated by Django 4.1.10 on 2023-11-30 15:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_bag_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='color',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='size',
        ),
        migrations.CreateModel(
            name='BagItems',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_items', to='products.bag')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
