# Generated by Django 4.1.10 on 2023-12-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_bag_razor_pay_order_id_bag_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='shipping_cost',
            field=models.IntegerField(default=0),
        ),
    ]
