# Generated by Django 4.1.10 on 2023-12-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_bag_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='shipping_cost',
            field=models.IntegerField(default=50),
        ),
    ]
